// ── Shared site data. Bilingual FR/EN, resolved at load via window.resolveI18n ──
window.JL = window.resolveI18n({
  brand: {
    name: "joliment",
    tagline: { fr: "Un endroit pour partager ce qui se construit ici, ce qu'on apprend, et pour rencontrer des gens qui ont envie de faire des trucs ensemble.", en: "A place to share what's being built here, what we learn, and to meet people who want to make things together." },
    mantra: "build · learn · collab",
    email: "hello@joliment.fr",
    locations: "Paris ↔ Phnom Penh",
    edition: { fr: "Édition 2026", en: "2026 Edition" },
    socials: [
      { l: "Instagram", h: "https://www.instagram.com/byjoliment" },
      { l: "LinkedIn", h: "https://www.linkedin.com/company/joliment" },
      { l: "GitHub", h: "https://github.com/jeanlisek" },
    ],
  },

  nav: [
    { slug: "accueil", label: { fr: "Accueil", en: "Home" }, href: "index.html", ic: "■" },
    { slug: "projets", label: { fr: "Projets", en: "Projects" }, href: "projets.html", ic: "▣" },
    { slug: "blog", label: { fr: "Blog", en: "Blog" }, href: "blog.html", ic: "≡" },
    { slug: "collab", label: { fr: "Collab", en: "Collab" }, href: "collab.html", ic: "◇" },
    { slug: "a-propos", label: { fr: "À propos", en: "About" }, href: "a-propos.html", ic: "○" },
  ],

  projets: [
    {
      slug: "mirakl", n: "01",
      title: "Hackathon Mirakl",
      sub: { fr: "6 agents Dust · Supply Brain", en: "6 Dust agents · Supply Brain" },
      desc: { fr: "Piloter une marketplace cross-canaux sans rupture ni surstock, conforme CSRD 2026. Cas d'usage Nordika Studio (200 SKUs sur Amazon FR/IT/DE et Google Shopping), avec 6 agents Dust orchestrés et un dashboard React personnalisable par profil.", en: "Steering a cross-channel marketplace with no stockouts or overstock, CSRD 2026 compliant. Nordika Studio use case (200 SKUs across Amazon FR/IT/DE and Google Shopping), with 6 orchestrated Dust agents and a React dashboard customizable per role." },
      tags: ["agents ia", "supply-chain", "marketplace", "hackathon"],
      badge: { fr: "Finaliste", en: "Finalist" },
      sigil: "bars",
      meta: { fr: "2026 · 5 jours", en: "2026 · 5 days" },
      durationNote: "build · 72h",
      gradient: "linear-gradient(135deg, #1a3a30 0%, #5a8a78 100%)",
      featured: true,
      role: { fr: "Lead conception · 7 personnes", en: "Design lead · 7 people" },
      stack: ["Dust.tt (6 agents)", "n8n Cloud", "Supabase", "React 19 + Vite", "OpenAI GPT‑4o", "MCP", "CSRD"],
      year: 2026,
      media: {
        video: { kind: "youtube", id: "eDhAxBXilQA", caption: { fr: "Démo vidéo — Hackathon Mirakl", en: "Video demo — Mirakl Hackathon" } },
        deck:  { kind: "iframe", src: "decks/mirakl-presentation.html", caption: "[TEAM 6] Mirakl — Pitch Deck" },
        photos: [
          "media/mirakl-photos/01.jpg", "media/mirakl-photos/02.jpg",
          "media/mirakl-photos/03.jpg", "media/mirakl-photos/04.jpg",
          "media/mirakl-photos/05.jpg", "media/mirakl-photos/06.jpg",
          "media/mirakl-photos/07.jpg",
        ],
      },
    },
    {
      slug: "synapse", n: "02",
      title: { fr: "Projet Synapse", en: "Synapse Project" },
      sub: { fr: "Chatbot RAG · thèses.fr", en: "RAG chatbot · thèses.fr" },
      desc: { fr: "Recherche sémantique sur corpus académique : embeddings + retrieval augmenté pour interroger des milliers de thèses en langage naturel, même sans correspondance exacte de mots.", en: "Semantic search over an academic corpus: embeddings + augmented retrieval to query thousands of theses in natural language, even without exact keyword matches." },
      tags: ["rag", "nlp", "embeddings", "ia"],
      sigil: "graph",
      meta: { fr: "2025 · Terminé", en: "2025 · Done" },
      gradient: "linear-gradient(135deg, #2a4858 0%, #5a8a9a 100%)",
      role: { fr: "Équipe · 4 personnes", en: "Team · 4 people" },
      stack: ["Python", "LangChain", "OpenAI Embeddings", "FAISS", "RAG"],
      year: 2025,
      media: {
        video: { kind: "youtube", id: "_GbsnNfgNIE", caption: { fr: "Démo vidéo — Projet Synapse", en: "Video demo — Synapse Project" } },
        repoLink: "https://github.com/jeanlisek/Synapse",
      },
    },
    {
      slug: "dust", n: "03",
      title: "Dust",
      sub: { fr: "Multi-agents orchestrés", en: "Orchestrated multi-agents" },
      desc: { fr: "Hub agentique sur Dust : faire collaborer plusieurs agents IA spécialisés plutôt qu'un seul généraliste, coordonnés par un orchestrateur. Base technique des projets IA suivants (Mirakl, PayFit).", en: "Agentic hub on Dust: having several specialized AI agents collaborate instead of one generalist, coordinated by an orchestrator. The technical foundation of the AI projects that followed (Mirakl, PayFit)." },
      tags: ["ia", "agents", "orchestration", "dust"],
      sigil: "orchestration",
      meta: { fr: "2025 · Terminé", en: "2025 · Done" },
      gradient: "linear-gradient(135deg, #3a2848 0%, #6a4a78 100%)",
      role: { fr: "Équipe · 3 personnes", en: "Team · 3 people" },
      stack: ["Dust", "Claude", "Multi-agents", "Orchestration", "Prompt engineering"],
      year: 2025,
      media: {
        video: { kind: "youtube", id: "QUS_q1Jho30", caption: { fr: "Démo vidéo — Dust Agent IA", en: "Video demo — Dust AI Agent" } },
      },
    },
    {
      slug: "payfit", n: "04",
      title: "Hackathon PayFit",
      sub: { fr: "9 agents Dust orchestrés", en: "9 orchestrated Dust agents" },
      desc: { fr: "Pipeline RH & Paie : chaque agent spécialisé dans une étape (recherche, rédaction, vérification légale, optimisation SEO) pour produire des articles publiables directement, sans retouche humaine.", en: "HR & Payroll pipeline: each agent specialized in one step (research, writing, legal review, SEO optimization) to produce directly publishable articles, with no human edits." },
      tags: ["ia", "agents", "seo", "rh & paie", "hackathon"],
      badge: { fr: "Finaliste", en: "Finalist" },
      sigil: "editorial",
      meta: { fr: "2026 · 5 jours", en: "2026 · 5 days" },
      durationNote: "build · 72h",
      gradient: "linear-gradient(135deg, #482830 0%, #8a4858 100%)",
      role: { fr: "CTO · 8 personnes", en: "CTO · 8 people" },
      stack: ["Dust", "Multi-agents", "Prompt engineering", "SEO"],
      year: 2026,
      media: {
        deck: { kind: "iframe", src: "https://docs.google.com/presentation/d/1v8I7LnIgwaD9GxyT_sakakkhFcZudv7n/embed?start=false&loop=false&delayms=5000", caption: "[TEAM] PayFit — Pitch Deck" },
        deckLink: "https://docs.google.com/presentation/d/1v8I7LnIgwaD9GxyT_sakakkhFcZudv7n/edit?usp=drive_link&ouid=102040317823571698021&rtpof=true&sd=true",
        photos: [
          "media/payfit-photos/01.jpg", "media/payfit-photos/02.jpg", "media/payfit-photos/03.jpg",
        ],
      },
    },
    {
      slug: "dashboard", n: "05",
      title: { fr: "Dashboard Financier", en: "Financial Dashboard" },
      sub: { fr: "Portefeuille automatisé · Sheets", en: "Automated portfolio · Sheets" },
      desc: { fr: "Dashboard financier maison : Google Sheets + Apps Script pour actualiser un portefeuille en temps réel, suivre les performances, et viser à battre le S&P500.", en: "Home-made financial dashboard: Google Sheets + Apps Script to refresh a portfolio in real time, track performance, and aim to beat the S&P500." },
      tags: ["finance", "google sheets", "apps script"],
      sigil: "finance",
      meta: { fr: "2025 · En suivi", en: "2025 · Tracking" },
      gradient: "linear-gradient(135deg, #2a3a28 0%, #6a8a58 100%)",
      role: { fr: "Équipe · 4 personnes", en: "Team · 4 people" },
      stack: ["Google Sheets", "Apps Script", { fr: "APIs financières", en: "Financial APIs" }],
      year: 2025,
      media: {
        deck: { kind: "iframe", src: "https://www.canva.com/design/DAG0RpImjpw/1e7hHKW0_qrx3xO7nBh7hw/view?embed", caption: { fr: "Présentation — Dashboard Financier", en: "Presentation — Financial Dashboard" } },
      },
    },
    {
      slug: "zigzag", n: "06",
      title: "ZigZag",
      sub: { fr: "Jeu multijoueur · from scratch", en: "Multiplayer game · from scratch" },
      desc: { fr: "Un jeu multijoueur web en temps réel construit de zéro avec des amis : de la mécanique au déploiement, sans framework dédié. Le projet qui a tout déclenché.", en: "A real-time multiplayer web game built from scratch with friends: from game mechanics to deployment, with no dedicated framework. The project that started it all." },
      tags: ["game dev", "multiplayer", "web"],
      sigil: "game",
      meta: { fr: "2025 · Live", en: "2025 · Live" },
      gradient: "linear-gradient(135deg, #1a2848 0%, #4a5a8a 100%)",
      role: { fr: "CTO · 4 personnes", en: "CTO · 4 people" },
      stack: ["JavaScript", "WebSocket", "Node.js", "HTML/CSS"],
      year: 2025,
      media: {
        live: { kind: "iframe", src: "https://zig-zag.fun", caption: { fr: "ZigZag — live sur zig-zag.fun", en: "ZigZag — live on zig-zag.fun" } },
        deck: { kind: "iframe", src: "https://www.canva.com/design/DAG_cLuhVSw/synMzn4iF9134bSFYLI5dA/view?embed", caption: "ZigZag — Pitch Deck" },
      },
    },
    {
      slug: "tableau", n: "07",
      title: "Data Viz Tableau",
      sub: { fr: "Olist Brasil · 99k commandes", en: "Olist Brasil · 99k orders" },
      desc: { fr: "Dashboard Tableau sur Olist : 99 441 commandes e-commerce brésiliennes (2016-2018), 8 vues consolidées avec filtres liés. São Paulo 42%, livraison 97%, pic Black Friday nov. 2017.", en: "Tableau dashboard on Olist: 99,441 Brazilian e-commerce orders (2016-2018), 8 consolidated views with linked filters. São Paulo 42%, 97% delivered, Black Friday peak Nov. 2017." },
      tags: ["tableau desktop", "data visualisation", "e-commerce", "dashboard"],
      sigil: "viz",
      meta: { fr: "2026 · Terminé", en: "2026 · Done" },
      gradient: "linear-gradient(135deg, #1a2a48 0%, #3a4a7a 100%)",
      role: { fr: "Équipe · 3 personnes", en: "Team · 3 people" },
      stack: ["Tableau Desktop", { fr: "CSV multi-tables", en: "Multi-table CSV" }, { fr: "Champs calculés", en: "Calculated fields" }, "DATEDIFF", { fr: "Carte choroplèthe", en: "Choropleth map" }, { fr: "Filtres liés", en: "Linked filters" }],
      year: 2026,
      media: {
        live: { kind: "iframe", src: "https://public.tableau.com/views/AnalyseOlist-Brsil2026-2018/AnalyseOlistBrsil2016-2018?:embed=y&:display_count=no&:showVizHome=no&:toolbar=no&:device=desktop&:size=1300,1000", caption: "Dashboard Olist Brasil — Tableau Public", aspect: "13 / 10" },
        deckLink: "https://public.tableau.com/app/profile/jean.li.sek/viz/AnalyseOlist-Brsil2026-2018/AnalyseOlistBrsil2016-2018",
      },
    },
    {
      slug: "sql", n: "08",
      title: { fr: "SQL · Accidents de la route", en: "SQL · Road Accidents" },
      sub: { fr: "Dashboard data.gouv.fr", en: "data.gouv.fr dashboard" },
      desc: { fr: "Analyse SQL des données data.gouv.fr sur les accidents de la route en France : zones, profils et conditions à risque, restitués dans un dashboard interactif déployé sur Vercel.", en: "SQL analysis of data.gouv.fr data on road accidents in France: high-risk zones, profiles and conditions, delivered in an interactive dashboard deployed on Vercel." },
      tags: ["sql", "data analyse", "datagouv", "visualisation"],
      sigil: "sql",
      meta: { fr: "2025 · Terminé", en: "2025 · Done" },
      gradient: "linear-gradient(135deg, #1a2a3a 0%, #4a6a8a 100%)",
      role: { fr: "Équipe · 4 personnes", en: "Team · 4 people" },
      stack: ["SQL", "Python", "data.gouv.fr", "Vercel", { fr: "visualisation", en: "visualization" }],
      year: 2025,
      media: {
        live: { kind: "iframe", src: "https://lumiastartup.vercel.app/?_vercel_share=dy5F5Uh8JS88yphBaOAtRkd97R7o6Y0s", caption: { fr: "Dashboard interactif — lumiastartup.vercel.app", en: "Interactive dashboard — lumiastartup.vercel.app" } },
        deck: { kind: "iframe", src: "https://www.canva.com/design/DAG3Md7Uh0A/v11w5dl5HTJ626glXIcVHw/view?embed", caption: { fr: "Présentation — Analyse SQL Accidents", en: "Presentation — SQL Accidents Analysis" } },
      },
    },
    {
      slug: "dataiku", n: "09",
      title: "Dataiku Cdiscount",
      sub: { fr: "Pipeline data science", en: "Data science pipeline" },
      desc: { fr: "Projet d'analyse Dataiku sur un dataset e-commerce réel de Cdiscount : exploration, nettoyage, modélisation, visualisation. Insights actionnables orientés performances produits et comportements d'achat.", en: "Dataiku analysis project on a real Cdiscount e-commerce dataset: exploration, cleaning, modeling, visualization. Actionable insights on product performance and buying behavior." },
      tags: ["dataiku", "analyse", "e-commerce", "data"],
      sigil: "ml",
      meta: { fr: "2026 · Terminé", en: "2026 · Done" },
      gradient: "linear-gradient(135deg, #1a3a48 0%, #4a7a8a 100%)",
      role: { fr: "Équipe · 4 personnes", en: "Team · 4 people" },
      stack: ["Dataiku", "Python", "Machine Learning", { fr: "Data visualisation", en: "Data visualization" }],
      year: 2026,
      media: {
        deck: { kind: "iframe", src: "decks/dataiku-presentation.html", caption: "[Groupe D] Dataiku — Dashboard CLV Cdiscount", hint: { fr: "↓ scroll pour explorer", en: "↓ scroll to explore" } },
      },
    },
    {
      slug: "discogs", n: "10",
      title: { fr: "Scraping Python · Discogs", en: "Python Scraping · Discogs" },
      sub: { fr: "Dataset vinyles · marché secondaire", en: "Vinyl dataset · resale market" },
      desc: { fr: "Scraping Discogs (la plus grande marketplace de vinyles) via Python pour analyser les corrélations entre format physique, rareté et valeur perçue sur le marché du vinyle d'occasion.", en: "Scraping Discogs (the largest vinyl marketplace) via Python to analyze the correlations between physical format, rarity and perceived value on the second-hand vinyl market." },
      tags: ["python", "scraping", "analyse", "musique"],
      sigil: "terminal",
      meta: { fr: "2025 · Terminé", en: "2025 · Done" },
      gradient: "linear-gradient(135deg, #3a2a1a 0%, #7a5a3a 100%)",
      role: { fr: "Équipe · 4 personnes", en: "Team · 4 people" },
      stack: ["Python", "BeautifulSoup", "Pandas", "Matplotlib", "Requests"],
      year: 2025,
      media: {
        deck: { kind: "iframe", src: "https://www.canva.com/design/DAG2hBBsOmc/akBnF4z10wT-kS5ISyadhg/view?embed", caption: { fr: "Présentation — Scraping Python Discogs", en: "Presentation — Python Scraping Discogs" } },
        repoLink: "https://github.com/jeanlisek/Python-Scrapping-Project-DISCOGS",
      },
    },
    {
      slug: "make", n: "11",
      title: { fr: "Make · Automatisation", en: "Make · Automation" },
      sub: { fr: "Workflows no-code en prod", en: "No-code workflows in prod" },
      desc: { fr: "Workflows no-code sur Make (ex-Integromat) pour connecter des applications, déclencher des actions automatiques et gérer des flux de données. Gain de temps mesurable sur des process manuels.", en: "No-code workflows on Make (ex-Integromat) to connect apps, trigger automatic actions and manage data flows. Measurable time saved on manual processes." },
      tags: ["make", "automatisation", "no-code", "workflows"],
      sigil: "flow",
      meta: { fr: "2025 · Terminé", en: "2025 · Done" },
      gradient: "linear-gradient(135deg, #2a2838 0%, #5a5a78 100%)",
      role: { fr: "Co-dev · 2 personnes", en: "Co-dev · 2 people" },
      stack: ["Make", "Webhooks", "APIs REST", "No-code"],
      year: 2025,
    },
    {
      slug: "kitchy", n: "12",
      title: "Hackathon Kitchy",
      sub: { fr: "Concept produit · pitch jury", en: "Product concept · jury pitch" },
      desc: { fr: "Hackathon startup en mode contraint : concept produit Kitchy de A à Z. Problème, proposition de valeur, prototype, pitch deck. De l'idée brute au pitch en moins de deux jours.", en: "Startup hackathon under constraint: the Kitchy product concept from A to Z. Problem, value proposition, prototype, pitch deck. From raw idea to pitch in under two days." },
      tags: ["hackathon", "startup", "produit"],
      sigil: "idea",
      meta: { fr: "2025 · 5 jours", en: "2025 · 5 days" },
      durationNote: "build · 72h",
      gradient: "linear-gradient(135deg, #382030 0%, #6a3858 100%)",
      role: { fr: "Équipe · 7 personnes", en: "Team · 7 people" },
      stack: ["Pitch deck", "Product design", { fr: "Prototypage", en: "Prototyping" }, "Canva"],
      year: 2025,
      media: {
        deck: { kind: "iframe", src: "https://www.canva.com/design/DAG4qQRhAzQ/gMBuIWLEpvBvw3q6143ksQ/view?embed", caption: "Pitch deck — Hackathon Kitchy" },
        deckLink: "https://www.canva.com/design/DAG4qQRhAzQ/gMBuIWLEpvBvw3q6143ksQ/view",
      },
    },
  ],

  pillars: [
    { title: { fr: "Reproductible", en: "Reproducible" }, body: { fr: "Chaque article inclut les étapes pour que tu puisses faire pareil sur ton ordi.", en: "Every article includes the steps so you can do the same on your own machine." } },
    { title: { fr: "Honnête", en: "Honest" }, body: { fr: "On documente ce qu'on a vraiment compris. Et ce qu'on n'a pas encore compris.", en: "We document what we actually understood. And what we haven't figured out yet." } },
    { title: { fr: "Concret", en: "Concrete" }, body: { fr: "Des outils réels, des cas d'usage réels, pas des exemples abstraits.", en: "Real tools, real use cases, no abstract examples." } },
  ],

  articles: [
    { slug: "docker", title: { fr: "Docker expliqué simplement. Et comment l'installer chez toi", en: "Docker explained simply. And how to install it at home" }, desc: { fr: "Comprendre Docker, pourquoi c'est utile. Et comment le faire tourner sur ta machine en moins de 10 minutes.", en: "Understanding Docker, why it's useful. And how to run it on your machine in under 10 minutes." }, cat: "infrastructure · docker", read: { fr: "8 min", en: "8 min" }, soon: true, sigil: "terminal" },
    { slug: "n8n", title: { fr: "n8n : automatise ta vie sans être développeur", en: "n8n: automate your life without being a developer" }, desc: { fr: "n8n c'est comme Make ou Zapier, mais open-source et auto-hébergeable. Installation et premier workflow utile. De zéro.", en: "n8n is like Make or Zapier, but open-source and self-hostable. Installation and a first useful workflow. From scratch." }, cat: "automatisation · n8n", read: { fr: "12 min", en: "12 min" }, soon: true, sigil: "nodes" },
    { slug: "agents", title: { fr: "Les agents IA, c'est quoi concrètement ?", en: "AI agents. What are they, concretely?" }, desc: { fr: "Derrière le buzzword \"agentique\", il y a quelque chose de simple et de puissant. Ce que c'est, comment ça fonctionne, et comment en construire un.", en: "Behind the \"agentic\" buzzword lies something simple and powerful. What it is, how it works, and how to build one." }, cat: "ia · agents", read: { fr: "10 min", en: "10 min" }, soon: true, sigil: "agents" },
    { slug: "dashboard-py", title: { fr: "Dashboard financier maison. Python, Google Sheets & App Script", en: "Home-made financial dashboard. Python, Google Sheets & App Script" }, desc: { fr: "Pas besoin d'un outil payant pour suivre ton portefeuille. Comment connecter Python, l'API Google Sheets et App Script pour un dashboard en temps réel.", en: "No paid tool needed to track your portfolio. How to connect Python, the Google Sheets API and App Script for a real-time dashboard." }, cat: { fr: "finance · outils", en: "finance · tools" }, read: { fr: "15 min", en: "15 min" }, soon: true, sigil: "finance" },
    { slug: "scraping", title: { fr: "Scraper un site avec Python. L'exemple Discogs", en: "Scrape a site with Python. The Discogs example" }, desc: { fr: "Le web scraping c'est une compétence sous-estimée. Comment récupérer des milliers de données depuis Discogs et les analyser.", en: "Web scraping is an underrated skill. How to pull thousands of data points from Discogs and analyze them." }, cat: "python · scraping", read: { fr: "10 min", en: "10 min" }, soon: true, sigil: "terminal" },
    { slug: "rag", title: { fr: "RAG. Construire un chatbot qui lit des thèses", en: "RAG. Building a chatbot that reads theses" }, desc: { fr: "Le Retrieval-Augmented Generation c'est l'un des patterns les plus utiles de l'IA actuelle. Walkthrough complet du projet Synapse, de l'embedding à la réponse finale.", en: "Retrieval-Augmented Generation is one of the most useful patterns in AI today. A full walkthrough of the Synapse project, from embedding to final answer." }, cat: "ia · rag", read: { fr: "14 min", en: "14 min" }, soon: true, sigil: "nodes" },
  ],

  skillsGroups: [
    { cat: "code", skills: [
      { l: "Python", k: "py", note: { fr: "Scraping, data analysis, APIs, automatisation", en: "Scraping, data analysis, APIs, automation" } },
      { l: "SQL", k: "sql", note: { fr: "Requêtes complexes, analyse, reporting", en: "Complex queries, analysis, reporting" } },
      { l: "R", k: "r", note: { fr: "Analyse statistique, modélisation, RStudio", en: "Statistical analysis, modeling, RStudio" } },
    ]},
    { cat: "data & viz", skills: [
      { l: "Data Engineering", k: "flow", note: { fr: "ETL, orchestration de flux, APIs, pipelines de données", en: "ETL, flow orchestration, APIs, data pipelines" } },
      { l: "Data Viz", k: "viz", note: "Tableau, PowerBI, Google Sheets, Looker, Dataiku" },
      { l: "Graph & BI", k: "graph", note: { fr: "Neo4j, Linkurious, modélisation en graphe", en: "Neo4j, Linkurious, graph modeling" } },
      { l: "Finance", k: "finance", note: { fr: "Analyse financière, états financiers, marchés, S&P500", en: "Financial analysis, statements, markets, S&P500" } },
    ]},
    { cat: "ia", skills: [
      { l: "RAG", k: "rag", note: { fr: "Embeddings, recherche sémantique, retrieval augmenté", en: "Embeddings, semantic search, augmented retrieval" } },
      { l: "Agents IA", k: "agents", note: { fr: "Dust, orchestration multi-agents, prompt engineering", en: "Dust, multi-agent orchestration, prompt engineering" } },
    ]},
    { cat: "infra & no-code", skills: [
      { l: "Docker", k: "docker", note: { fr: "Conteneurisation, déploiement, environnements isolés", en: "Containerization, deployment, isolated environments" } },
      { l: "Automatisation", k: "flow", note: { fr: "Make, n8n, Apps Script, workflows no-code", en: "Make, n8n, Apps Script, no-code workflows" } },
      { l: "Web", k: "py", note: "HTML/CSS/JS, Next.js, Tailwind" },
    ]},
  ],

  languages: [
    { code: "FR", name: { fr: "Français", en: "French" }, level: { fr: "Natif", en: "Native" } },
    { code: "EN", name: { fr: "Anglais", en: "English" }, level: "TOEIC 940 · B2" },
    { code: "KM", name: { fr: "Khmer", en: "Khmer" }, level: { fr: "Courant", en: "Fluent" } },
    { code: "DE", name: { fr: "Allemand", en: "German" }, level: "B1" },
  ],

  testimonials: [
    { id: "ml", initials: "ML", n: "Matthieu L.", r: { fr: "Enseignant Python · M1 AI Applied to Business", en: "Python teacher · M1 AI Applied to Business" }, q: { fr: "Jean-Li s'est rapidement distingué par son sens de l'initiative et son engagement tout au long du Master. Attentif, impliqué, toujours prêt à proposer des idées pertinentes.", en: "Jean-Li quickly stood out for his initiative and his commitment throughout the Master's. Attentive, involved, always ready to bring up relevant ideas." } },
    { id: "kp", initials: "KP", n: "Kevin Rosamont Prombo", r: { fr: "Enseignant SQL & Google Sheets · M1 AI Applied to Business", en: "SQL & Google Sheets teacher · M1 AI Applied to Business" }, q: { fr: "Jean-Li fait partie de ces étudiants qui dépassent rapidement le cadre du cours. Sur SQL comme sur Google Sheets, il transforme chaque notion vue en classe en un projet concret et abouti. Toujours avec rigueur et une vraie curiosité pour aller chercher la réponse.", en: "Jean-Li is one of those students who quickly go beyond the scope of the course. On SQL as on Google Sheets, he turns every concept seen in class into a concrete, polished project. Always with rigor and genuine curiosity to dig for the answer." }, src: "media/kevin-rosamont.jpeg" },
    { id: "te", initials: "TE", n: "Thomas Escot", r: { fr: "Enseignant Digital Marketing · Consultant SEO/GEO", en: "Digital Marketing teacher · SEO/GEO consultant" }, q: { fr: "J'ai eu Jean-Li en cours de Digital Marketing, dans le cadre d'un projet réel de stratégie SEO/GEO déployée de A à Z. Son travail m'a marqué par sa capacité à produire des recommandations à la fois techniquement solides et parfaitement ancrées dans les contraintes réelles du site. Mention spéciale pour l'outil d'automatisation développé avec son groupe : c'est exactement le niveau d'initiative et de maîtrise qu'on attend d'un profil qui se distingue.", en: "I taught Jean-Li in Digital Marketing, on a real SEO/GEO strategy project deployed end to end. His work struck me by its ability to produce recommendations that were both technically solid and perfectly grounded in the site's real constraints. Special mention for the automation tool built with his group: exactly the level of initiative and mastery you expect from a standout profile." }, src: "media/thomas-escot.jpeg" },
    { id: "ap", initials: "AP", n: "Élie Zemmour & Mathieu Turban", r: { fr: "Founding Partners · Awake Partners", en: "Founding Partners · Awake Partners" }, q: { fr: "Jean-Li est une véritable « machine » : il a porté le développement et la croissance d'Awake Partners avec une rigueur, une ingéniosité et un dynamisme à toute épreuve. Très orienté data et résultats, il a su apporter des solutions créatives et pragmatiques à chaque défi rencontré.", en: "Jean-Li is a real \"machine\": he drove the development and growth of Awake Partners with relentless rigor, ingenuity and energy. Very data- and results-driven, he brought creative, pragmatic solutions to every challenge faced." }, src: "media/logo-awake.jpeg" },
  ],

  collabs: [
    {
      slug: "veille-ia",
      tags: ["ia", "automatisation", "saas"],
      title: { fr: "Outil de veille IA pour PME", en: "AI monitoring tool for SMBs" },
      desc: { fr: "Un outil pour aider des PME à suivre leur secteur automatiquement. Articles, brevets, signaux faibles. En cours de conception.", en: "A tool to help SMBs monitor their industry automatically. Articles, patents, weak signals. Currently in design." },
      seek: { fr: "quelqu'un de curieux sur l'IA et/ou le product.", en: "someone curious about AI and/or product." },
      status: "open",
      slots: { fr: "1–2 personnes", en: "1–2 people" },
      step: { fr: "Conception · début dév", en: "Design · early dev" },
    },
    {
      slug: "joliment-v2",
      tags: ["web", "communauté", "no-code"],
      title: "joliment.fr v2",
      desc: { fr: "Ce site lui-même évolue. Vers une vraie communauté de builders. Édition collaborative, fil d'updates, espaces projet.", en: "This very site is evolving. Toward a real community of builders. Collaborative editing, update feed, project spaces." },
      seek: { fr: "designer, dev front, ou simplement quelqu'un avec de bonnes idées.", en: "designer, front-end dev, or simply someone with good ideas." },
      status: "open",
      slots: { fr: "ponctuel", en: "occasional" },
      step: { fr: "En cours · v.2.4", en: "Ongoing · v.2.4" },
    },
    {
      slug: "dashboard-v2",
      tags: ["finance", "data", "python"],
      title: { fr: "Dashboard Financier v2", en: "Financial Dashboard v2" },
      desc: { fr: "La prochaine version du dashboard financier. De vraies stratégies quantitatives, pas juste du suivi. Backtesting, alertes, signaux.", en: "The next version of the financial dashboard. Real quant strategies, not just tracking. Backtesting, alerts, signals." },
      seek: { fr: "quelqu'un avec un intérêt pour la finance et des bases en Python ou data.", en: "someone interested in finance with basics in Python or data." },
      status: "soon",
      slots: { fr: "1 personne", en: "1 person" },
      step: { fr: "Idéation", en: "Ideation" },
    },
  ],

  about: {
    quote: "A dream you dream alone is only a dream. A dream you dream together is reality.",
    cite: "— John Lennon",
    name: "Jean-Li Sek",
    titleLine: { fr: "Data & IA · Builder · Apprenant à plein temps.", en: "Data & AI · Builder · Full-time learner." },
    intro: { fr: "J'ai grandi avec l'idée qu'on peut apprendre à peu près n'importe quoi si on s'y met vraiment. Ce site, c'est la trace de tout ce que j'explore. Pas pour impressionner, mais pour documenter le chemin et partager ce qui peut être utile.", en: "I grew up with the idea that you can learn just about anything if you really commit to it. This site is the trace of everything I explore. Not to impress, but to document the journey and share what might be useful." },
    longBio: [
      { fr: "J'ai grandi avec l'idée qu'on peut apprendre à peu près n'importe quoi si on s'y met vraiment. Ce site c'est la trace de tout ce que j'ai exploré. Pas pour impressionner, mais pour documenter ce chemin et partager ce qui peut être utile aux autres.", en: "I grew up with the idea that you can learn just about anything if you really commit to it. This site is the trace of everything I've explored. Not to impress, but to document that journey and share what might be useful to others." },
      { fr: "Je travaille sur des sujets très variés : de la data science à l'automatisation, des agents IA à la finance quantitative, du développement web au conseil en transformation. Ce que j'aime, c'est quand ces domaines se croisent et créent quelque chose d'inattendu.", en: "I work across very varied topics: from data science to automation, from AI agents to quantitative finance, from web development to transformation consulting. What I love is when these fields cross and create something unexpected." },
      { fr: "En dehors du code et de la data, je joue de la guitare et du piano, je m'intéresse aux marchés financiers, et je suis convaincu qu'on apprend mieux en faisant qu'en regardant.", en: "Beyond code and data, I play guitar and piano, I follow the financial markets, and I'm convinced you learn better by doing than by watching." },
    ],
    formation: [
      { period: { fr: "2025. Aujourd'hui", en: "2025. Present" }, body: "M1 AI Applied to Business" },
      { period: "2024. 2025", body: { fr: "L3 Économie Gestion. Parcours Finance Comptabilité Contrôle", en: "BSc 3 Economics & Management. Finance, Accounting & Control track" } },
      { period: "2023. 2024", body: { fr: "L2 Économie Gestion. Parcours général", en: "BSc 2 Economics & Management. General track" } },
      { period: "2022. 2023", body: { fr: "L1. PluriPass (1ère année commune aux études de santé)", en: "BSc 1. PluriPass (pre-med common first year)" }, faint: true },
    ],
    experiences: [
      { period: { fr: "Mars 2026. Aujourd'hui", en: "March 2026. Present" }, body: { fr: "Consultant Data & IA (alternance)", en: "Data & AI Consultant (apprenticeship)" } },
      { period: { fr: "Sept. 2025. Fév. 2026", en: "Sept. 2025. Feb. 2026" }, body: { fr: "Chef de Projet Communication & Marketing. Bras Droit Présidente", en: "Communication & Marketing Project Lead. Right hand to the President" }, faint: true },
      { period: { fr: "2023. Aujourd'hui", en: "2023. Present" }, body: { fr: "Création de Joliment. Auto-entreprise", en: "Founded Joliment. Sole proprietorship" } },
    ],
    interests: [
      { fr: "Musique. Guitare, piano, et tout ce qui m'accompagne au quotidien", en: "Music. Guitar, piano, and everything that scores my day-to-day" },
      { fr: "Voyages. Les destinations qui dépaysent vraiment et changent la perspective", en: "Travel. Destinations that truly shift you and change your perspective" },
      { fr: "Sport. Escalade, tennis, running", en: "Sport. Climbing, tennis, running" },
      { fr: "Photographie & vidéo. Capturer ce qui mérite de rester", en: "Photography & video. Capturing what deserves to last" },
    ],
    currently: [
      { fr: "Ce site. Joliment.fr", en: "This site. Joliment.fr" },
      { fr: "Blog. Premiers articles en cours", en: "Blog. First articles in progress" },
      { fr: "Next trip. Destination à confirmer", en: "Next trip. Destination TBC" },
      { fr: "Tenir bon. Un jour à la fois", en: "Holding steady. One day at a time" },
    ],
    supportDesc: { fr: "Joliment reverse une partie de ses revenus à deux associations qui nous tiennent à cœur.", en: "Joliment donates part of its revenue to two charities close to our hearts." },
    associations: [
      { name: "France Parkinson", href: "https://www.franceparkinson.fr", desc: { fr: "Recherche & accompagnement", en: "Research & support" } },
      { name: "Résilience Enfants d'Asie", href: "https://www.resilienceenfantsdasie.org/page/82066-accueil", desc: { fr: "Éducation au Cambodge", en: "Education in Cambodia" } },
    ],
  },

  travelStops: [
    { id: "trv-cph-1", src: "media/photos/02-iridescent-glass.jpeg", loc: "Copenhagen", sub: { fr: "Royal Library. Vitrine iridescente", en: "Royal Library. Iridescent glass" } },
    { id: "trv-cph-2", src: "media/photos/04-black-diamond.jpeg", loc: "Copenhagen", sub: { fr: "Black Diamond, sur l'eau", en: "Black Diamond, on the water" } },
    { id: "trv-cph-3", src: "media/photos/07-spire-frame.jpeg", loc: "Copenhagen", sub: { fr: "Vor Frelsers, encadrée", en: "Vor Frelsers, framed" } },
    { id: "trv-cph-4", src: "media/photos/03-copenhagen-by-heart.jpeg", loc: "Copenhagen", sub: { fr: "By Heart, en néon", en: "By Heart, in neon" } },
    { id: "trv-cph-5", src: "media/photos/05-spheres-copenhagen.jpeg", loc: "Copenhagen", sub: { fr: "Sphères, regard levé", en: "Spheres, looking up" } },
    { id: "trv-ams-1", src: "media/photos/06-rijksmuseum.jpeg", loc: "Amsterdam", sub: { fr: "Rijksmuseum, depuis l'eau", en: "Rijksmuseum, from the water" } },
    { id: "trv-mirror", src: "media/photos/01-mirror-reflet.jpeg", loc: { fr: "Quelque part", en: "Somewhere" }, sub: { fr: "Reflet, bateau, miroir cassé", en: "Reflection, boat, broken mirror" } },
  ],

  thisWeek: [
    { day: { fr: "Lun. 19", en: "Mon. 19" }, text: { fr: "Article Docker. Publication prévue jeudi.", en: "Docker article. Publishing Thursday." } },
    { day: { fr: "Mer. 21", en: "Wed. 21" }, text: { fr: "Synapse v2. Ajout de nouveaux corpus.", en: "Synapse v2. Adding new corpora." } },
    { day: { fr: "Ven. 23", en: "Fri. 23" }, text: { fr: "Nouvelle position collab ouverte.", en: "New collab position opened." } },
  ],
});
